### ISSUE TITLE
Adding tags to the database

### ISSUE THREAD

**Issue by kamillastefania** [mattfelsen/mfadt-thesis-website-2014#11]
Add tags to the database and other functionality needed so people can start adding tags to their profiles.

**Comment by mattfelsen** [comment]
Tags are fully functional! You can pull from git & make sure you do the database import. Note: WordPress normally displays an empty text box for tags and autocompletes as you type. Not helpful if you don't know what the available tags are though! I added a plugin which, when logged in as a student, display a list of checkboxes that looks just like categories. If you're logged in as the mfadt admin account it will show as the normal text box.

Via commit 18ef2121162d729aeb8e91d5da7da17ab87a6932
