### ISSUE TITLE
Detail page: Student bio overflowing

### ISSUE THREAD

**Issue by mattfelsen** [mattfelsen/mfadt-thesis-website-2014#16]
Long bios flow into the next section. Is there a height/max-height setting on the container? See Clarissa for an example:
http://dev.mfadt.com/2014/project/narrative-mechanisms

![screen shot 2014-04-27 at 11 45 02 pm](https://cloud.githubusercontent.com/assets/2334552/2832161/c520bb38-cfc1-11e3-844f-5599ffe2a486.png)

**Comment by qkbock** [comment]
Yeah I saw this just a few min ago with Richardo...

How do we want to deal with it?  Have scrollable text? just cut it off?
I assume we are telling people that they have a limit when they input it?

Quincy

**Comment by mattfelsen** [comment]
Why not just let the container expand to fit the content? There's no specified limit on bios, Kamilla's email is the only place it's been advertised, and that only metions a "short bio" about yourself

**Comment by qkbock** [comment]
sure we can do that.  I just didnt do it that way cause we had said before
that we would have a character limit so i tried to make it look best with
the headshot but doesnt matter one way or the other
