### ISSUE TITLE
Put students' symposium date + info next to their bio

### ISSUE THREAD

**Issue by binaricorn** [mattfelsen/mfadt-thesis-website-2014#27]

**Comment by mattfelsen** [comment]
Hm. GitHub won't let you assign an issue to multiple people. Lame! Anyway, if you go to the custom fields section, WP-Types has a Date field and you can select to use both date & time. I haven't seen what the date/time picker looks like, but it sounds like exactly what we need

**Comment by binaricorn** [comment]
We still need to figure out how to link this to timeline.js or whatever we're using, but:

![screen shot 2014-05-03 at 2 01 57 pm](https://cloud.githubusercontent.com/assets/2773387/2871003/0f84cda8-d2ed-11e3-8914-6a402587838b.png)
