### ISSUE TITLE
Missing faculty info on project's detail page

### ISSUE THREAD

**Issue by kamillastefania** [mattfelsen/mfadt-thesis-website-2014#32]
For students who have had John Sharp as their thesis faculty for both semesters only one of the writing&research faculty is displayed on project's section. 
Basically, when the thesis faculty stayed the same for both semesters it automatically assigns the writing&research faculty from the fall semester to it and doesn't display the spring one.

Same problem may happen to students who have had Melanie as a thesis faculty for both semester.

See: http://dev.mfadt.com/2014/project/tbd-3

**Comment by mattfelsen** [comment]
Fixed in 0e0784f
